services:
  postgres:
    image: postgres:16
    container_name: emotion-postgres
    environment:
      POSTGRES_DB: emotion_db
      POSTGRES_USER: emotion_user
      POSTGRES_PASSWORD: emotion_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
