spring:
  application:
    name: emotion-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/emotion_db
    username: emotion_user
    password: emotion_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# Agent Server
agent:
  server:
    url: http://localhost:8000
